project:
  type: book
  output-dir: _site
  resources:
    - images


book:
  title: "STRAT 325 - Intro to Management Consulting"
  favicon: favicon.svg
  author: "Scott Murff"
  date: "Winter 2026"
  chapters:
    - part: "Course Info"
      chapters:
        - index.qmd
        - 00-schedule.qmd
        - 00-assessments.qmd
    - part: "Foundation"
      chapters:
        - 01-what-is-consulting.qmd
        - 02-consultants-os.qmd
        - 03-leveraging-ai.qmd
        - 04-working-as-a-team.qmd
    - part: "The Four Imperatives"
      chapters:
        - 05-think-clearly.qmd
        - 06-get-right-answer.qmd
        - 07-move-work-forward.qmd
        - 08-create-impact.qmd
    - part: "Course Goals"
      chapters:
        - 09-land-an-offer.qmd
        - 10-do-client-work.qmd
    - part: "Resources"
      chapters:
        - 97-activities.qmd
        - 97-ta-handbook.qmd
        - 98-resources.qmd
        - 99-references.qmd

bibliography: references.bib
# csl: informs.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    markdown: default
    number-sections: false

toc-title: On this page

number-sections: true
